### ISSUE TITLE
Legendary Mythic & Admin are the only ones working for Modded items

### ISSUE THREAD

**Issue by Gamerbolts** [Globox1997/TooltipRareness#10]
Hello! I am trying to set rarities for all my items in my large modpack. As I went to test it I found only Legendary, Mythic and Admin are working. All the ones I set to Common/Uncommon/Rare/Epic do not show up. Here is my zip file
[Rarities.zip](https://github.com/Globox1997/TooltipRareness/files/10310738/Rarities.zip)

Logs if they help
[latest.log](https://github.com/Globox1997/TooltipRareness/files/10310751/latest.log)

Not too sure why that is happening, Hope you can help. Thanks!

**Comment by Globox1997** [comment]
This is an issue by the datapack part of your rarities zip file. Read the latest log and it will say why the specific tags didn't load.
For epic_item tag it says:
```
[15:05:18] [Worker-Main-17/ERROR]: Couldn't read tag list tooltiprareness:epic_item from tooltiprareness:tags/items/epic_item.json in data pack Rarities.zip
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 28 column 4 path $.values[24]
	at com.google.gson.internal.Streams.parse(Streams.java:60) ~[gson-2.8.9.jar:?]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:85) ~[gson-2.8.9.jar:?]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:60) ~[gson-2.8.9.jar:?]
	at net.minecraft.class_3503.method_33174(class_3503.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3503.method_33176(class_3503.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_3505.method_33181(class_3505.java:64) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 28 column 4 path $.values[24]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:475) ~[gson-2.8.9.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:675) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:684) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar:?]
	at com.google.gson.internal.Streams.parse(Streams.java:48) ~[gson-2.8.9.jar:?]
	... 12 more
```

**Comment by Gamerbolts** [comment]
Apparently I missed some "," oops. Thank you!
